# Generated by Django 6.0.6 on 2026-06-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nombre_processeur', models.PositiveIntegerField()),
                ('capacite_memoire', models.PositiveIntegerField()),
                ('capacite_stockage', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'serveur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeServeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'type_serveur',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100, unique=True)),
                ('date_lancement', models.DateField()),
                ('espace_memoire_utilise', models.PositiveIntegerField()),
                ('memoire_vive_necessaire', models.PositiveIntegerField()),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='inventory.serveur')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['nom_service'],
            },
        ),
        migrations.AddField(
            model_name='serveur',
            name='type_serveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serveurs', to='inventory.typeserveur'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='inventory.utilisateur')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['nom_application'],
            },
        ),
        migrations.CreateModel(
            name='UsageRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages_ressource', to='inventory.application')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages_ressource', to='inventory.service')),
            ],
            options={
                'db_table': 'usage_ressource',
                'unique_together': {('application', 'service')},
            },
        ),
    ]
